ENH: Lowering required nibabel version to 1.2.0
Confirmed failure to pickle with earlier nibabels

======================================================================
ERROR: test_dataset_save (neurosynth.tests.test_base.TestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File /home/yoh/proj/neurosynth/Neurosynth/neurosynth/tests/test_base.py, line 20, in test_dataset_save
    self.dataset.save(t)
  File /home/yoh/proj/neurosynth/Neurosynth/neurosynth/base/dataset.py, line 301, in save
    cPickle.dump(self, open(filename, 'wb'), -1)
PicklingError: Can't pickle <class 'nibabel.analyze.ImageArrayProxy'>: attribute lookup nibabel.analyze.ImageArrayProxy failed